### ISSUE TITLE
Compatibility with older JMeter

### ISSUE THREAD

**Issue by Milanista99** [zalopay-oss/jmeter-grpc-plugin#10]
Hello,

I would like to ask if this plugin could work with JMeter version 2.9? I've tried to add it, but I get the following error:
2020/06/04 12:50:39 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoSuchMethodError: org.apache.jmeter.samplers.SampleResult.setSentBytes(J)V
	at vn.zalopay.jmeter.grpc.client.ClientRecorder.<init>(ClientRecorder.java:18)
	at vn.zalopay.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:93)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Thread.java:748)

Regards
Miky

**Comment by thoainguyen** [comment]
Hi @Milanista99, 
Try to remove [that line](https://github.com/zalopay-oss/jmeter-grpc-plugin/blob/master/src/main/java/vn/zalopay/jmeter/grpc/client/ClientRecorder.java#L18), and re-install. Without the code `.setSentBytes()`, the column `Network (KB/sec)/Sent` will be missing but the jmeter plugin still work
BR.
Thoai nguyen

**Comment by Milanista99** [comment]
Thank you for the help, it works :)
